name: CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    Linter:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
            - name: Install modules
              run: yarn
            - name: Run ESLint
              run: yarn lint
    Formater:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
            - name: Install modules
              run: yarn
            - name: Run Prettier
              run: yarn check-formatting
